#!/bin/bash
export HOME=/config/rtorrent
export PWD=/config/rtorrent

s6-setuidgid rtorrent \
rtorrent -D -I -n \
    -o "import=/etc/rtorrent/rtorrent.rc$(find /etc/rtorrent/conf.d/ -iname '*.rc' -type f | xargs -n1 printf ',import=%s')"
